apiVersion: apps/v1
kind: Deployment
metadata:
  name: rms-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rms
  template:
    metadata:
      labels:
        app: rms
    spec:
      containers:
      - name: rms-container
        image: rms-app
        imagePullPolicy: Never
        ports:
        - containerPort: 8080