apiVersion: v1
kind: Service
metadata:
  name: donation-service
spec:
  selector:
    app: donation-app
  ports:
    - protocol: TCP
      port: 80          # Service port (external)
      targetPort: 8080  # Container port (your app runs here)
  type: NodePort